FROM nginx:alpine
ADD nginx.sites /etc/nginx/conf.d/default.conf
ADD index.html /var/www/site/index.html
ADD tapas /var/www/site/tapas
ADD local-tapas-config.js /var/www/site/tapas/local-tapas-config.js
